## Problem 1: Creating basic geometries (*5 points*)


1: Create a function called `create_point_geom()` that has two parameters (x_coord, y_coord). Function should create a shapely `Point` geometry object and return that. 
   

In [1]:
from shapely.geometry import Point, LineString, Polygon
def create_point_geom(x_coord, y_coord):
    """
    Function for creating a point

    Parameters
    ----------
    x_coord: <numerical>
        x coordinate of point
    y_coord: <numerical>
        y coordinate of point

    Returns
    -------
    <Point>
        a shapely Point
    """
    return Point(x_coord, y_coord)

Test your function by running these code cells:

In [2]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
# Demonstrate the usage of the function
point1 = create_point_geom(0.0, 1.1)

In [3]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
print(point1)

POINT (0 1.1)


In [4]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
print(point1.geom_type)

Point


2: Create a function called **`create_line_geom()`** that takes a list of Shapely Point objects as parameter called **`points`** and returns a LineString object of those input points. In addition, you should take care that the function is used as it should:

  - Inside the function, you should first check with `assert` -functionality that the input is a **list** (see [lesson 6 from the Geo-Python course](https://geo-python.github.io/site/lessons/L6/interpreting-errors.html#assertions) and [hints for this exercise](https://automating-gis-processes.github.io/site/develop/lessons/L1/exercise-1.html#hints)). If something else than a list is passed for the function, you should return an Error message: `"Input should be a list!"`
  - You should also check with `assert` that the input list contains **at least** two values. If not, return an Error message: `"LineString object requires at least two Points!"`
  - Optional: Finally, you should check with `assert` that all values in the input list are truly Shapely Points. If not, return an Error message: `"All list values should be Shapely Point objects!"`
  

In [5]:
def create_line_geom(points):
        """
    Function for creating a line

    Parameters
    ----------
    points: <list>
        list of points connecting line

    Returns
    -------
    <LineString>
        a shapely line
    """
    assert type(points) == list, 'Input should be a list!'
    assert len(points) >= 2, 'LineString object requires at least two Points!'
    return LineString(points)

# Demonstrate the usage of your function; For example, create a line object with two points: `Point(45.2, 22.34)` & `Point(100.22, -3.20)` and store the result in a variable called `line1`:

In [6]:
line1 = None
line1 = create_line_geom([Point(45.2, 22.34),Point(100.22, -3.20)])

Run these code cells to check your solution:

In [7]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
print(line1)

LINESTRING (45.2 22.34, 100.22 -3.2)


In [8]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
print(line1.geom_type)

LineString


Check if your function checks the input correctly by running this code cell:

In [9]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
try:
    # Pass something else than a list
    create_line_geom("Give me a line!")
except AssertionError:
    print("List check works")
except Exception as e:
    raise e

List check works


3: Create a function called **`create_poly_geom()`** that has one parameter called **`coords`**. `coords` parameter should containt **a list of coordinate tuples**. The function should create and return a Polygon object based on these coordinates.  

  - Inside the function, you should first check with `assert` -functionality that the input is a **list** (see [lesson 6](https://geo-python.github.io/site/lessons/L6/interpreting-errors.html#assertions) and [hints](https://automating-gis-processes.github.io/site/develop/lessons/L1/exercise-1.html#hints)). If something else than a list is passed for the function, you should return an Error message: `"Input should be a list!"`
  - You should also check with `assert` that the input list contains **at least** three values. If not, return an Error message: `"Polygon object requires at least three Points!"`
  - Check the data type of the objects in the input list. All values in the input list should be tuples. If not, return an error message: "All list values should be coordinate tuples!" using assert.
  - **Optional:** Allow also an input containing a list of Shapely Point objects. If `coors` contans a list of Shapely Point objects, return a polygon based on these points. If the input is neither a list of tuples, nor a list of Points, return an appropriate error message using assert.
  

In [28]:
def create_poly_geom(coords):
        """
    Function for creating a polygon

    Parameters
    ----------
    coords: <tuple>
        list of points connecting polygon        

    Returns
    -------
    <Polygon>
        a shapely polygon
    """
    assert len(coords) >= 3, 'Polygon object requires at least three Points!'
    assert type(coords) == tuple, 'All list values should be coordinate tuples!'
    return Polygon(coords)

Demonstrate the usage of the function. For example, create a Polygon with three points: `(45.2, 22.34)`, `(100.22, -3.20)` & `(70.0, 10.20)`.

In [29]:
poly1 = None
poly1 = create_poly_geom(((45.2, 22.34), (100.22, -3.20), (70.0, 10.20)))

In [30]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
print(poly1)

POLYGON ((45.2 22.34, 100.22 -3.2, 70 10.2, 45.2 22.34))


In [24]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
print(poly1.geom_type)

Polygon


Check if your function checks the length of the input correctly by running this code cell:

In [25]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
try:
    # Pass something else than a list
    create_poly_geom("Give me a polygon")
except AssertionError:
    print("List check works")
except Exception as e:
    raise e

List check works


- Upload the codes and edits to your **own** personal GitHub repository for Exercise-1

## Done!

That's it. Now you are ready to continue with Problem 2. 

## Problem 2: Attributes of geometries (*5 points*)

1: Create a function called `get_centroid()` that has one parameter called `geom`. The function should take any kind of Shapely's geometric -object as an input, and return a centroid of that geometry. In addition, you should take care that the function is used as it should:

  - Inside the function, you should first check with `assert` -functionality that the input is a Shapely Point, LineString or Polygon geometry (see [lesson 6](https://geo-python.github.io/site/lessons/L6/interpreting-errors.html#assertions) and [hints](https://automating-gis-processes.github.io/site/develop/lessons/L1/exercise-1.html#hints)). If something else than a list is passed for the function, you should return an Error message: `"Input should be a Shapely geometry!"`


In [109]:
def get_centroid(geom):
        """
    Function for finding a centroid

    Parameters
    ----------
    geom: <Point, LineString, Polygon>
        takes a point, line, or polygon
   

    Returns
    -------
    <float>
        the objects centroid
    """
    assert type(geom) == Point or type(geom) == LineString or type(geom) == Polygon, 'Input should be a Shapely geometry!'
    return geom.centroid

Test and demonstrate the usage of the function. You can, for example, create shapely objects using the functions you created in problem 1 and print out information about their centroids:


In [99]:
poly1.geom_type == 'Polygon'

True

In [108]:
type(line1) == LineString

True

In [110]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
centroid = get_centroid(poly1)
print(centroid)

POINT (71.80666666666667 9.780000000000001)


Check that the assertion error works correctly:

In [111]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
try:
    # Pass something else than a Shapely geometry
    get_centroid("Give me a centroid!")
except AssertionError:
    print("Geometry -check works")
except Exception as e:
    raise e

Geometry -check works


2: Create a function called `get_area()` with one parameter called `polygon`. Function should take a Shapely's Polygon -object as input and returns the area of that geometry. 
   
   - Inside the function, you should first check with `assert` -functionality that the input is a Shapely Polygon geometry (see [lesson 6](https://geo-python.github.io/site/lessons/L6/interpreting-errors.html#assertions) and [hints](https://automating-gis-processes.github.io/site/develop/lessons/L1/exercise-1.html#hints)). If something else than a list is passed for the function, you should return an Error message: `"Input should be a Shapely Polygon -object!"`

In [112]:
def get_area(polygon):
        """
    Function for finding the area of a polygon

    Parameters
    ----------
    polygon: <Polygon>
        a shapely Polygon

    Returns
    -------
    <float>
        area of the polygon
    """
    assert type(polygon) == Polygon, 'Input should be a Shapely Polygon -object!'
    return polygon.area

Test and demonstrate the usage of the function:

In [113]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
area = get_area(poly1)
print(round(area, 2))

17.28


Check that the assertion works:

In [114]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
try:
    # Pass something else than a Shapely geometry
    get_area("Give me an area!")
except AssertionError:
    print("Geometry -check works")
except Exception as e:
    raise e

Geometry -check works


3: Create a function called `get_length()` with parameter called `geom`. The function should accept either a Shapely LineString or Polygon -object as input. Function should check the type of the input and returns the length of 
the line if input is LineString and length of the exterior ring if input is Polygon. If something else is passed to the function, you should return an `Error` `"'geom' should be either LineString or Polygon!"`. (Use assert functionality). 


In [115]:
def get_length(geom):
        """
    Function for finding the length of a line or polygon

    Parameters
    ----------
    geom: <LineString, Polygon>
        shapely Linestring or polygon


    Returns
    -------
    <float>
        length of line or perimeter of polygon
    """
    assert type(geom) == LineString or type(geom) == Polygon, '"geom" should be either LineString or Polygon!'
    return geom.length

Test and demonstrate the usage of the function:

In [116]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
line_length = get_length(line1)
print("Line length:", round(line_length,2))

Line length: 60.66


In [117]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
poly_exterior_length = get_length(poly1)
print("Polygon exterior length:", round(poly_exterior_length,2))

Polygon exterior length: 121.33


In [118]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION
try:
    # Pass something else than a Shapely LineString or Polygon
    get_length(Point(1,2))
except AssertionError:
    print("Geometry -check works")
except Exception as e:
    raise e

Geometry -check works


## Docstrings

Did you add a docstring to all the functions you defined? If not, add them now :) A short one-line docstring is enough in this exercise.

YOUR ANSWER HERE

In addition, you can run the code cell below to check all the docstrings!

In [ ]:
# NON-EDITABLE CODE CELL FOR TESTING YOUR SOLUTION

# List all functions we created
functions = [create_point_geom, create_line_geom, create_poly_geom, get_centroid,
            get_area, get_length]

print("I created functions for doing these tasks:\n")

for function in functions:
    #Print function name and docstring:
    print("-", function.__name__ +":", function.__doc__)

- Upload the codes and edits to your **own** personal GitHub repository for Exercise-1.

## Done!

That's it. Now you are ready to continue with Problem 3. 